version: '2'
services:
 zookeeper:
  image: confluentinc/cp-zookeeper:5.5.1
  hostname: zookeeper
  container_name: zookeeper
  ports:
   - "2181:2181"
  environment:
   ZOOKEEPER_TICK_TIME: 2000
   ZOOKEEPER_INIT_LIMIT: 10
   ZOOKEEPER_SYNC_LIMIT: 5
   ZOOKEEPER_CLIENT_PORT: 2181
  networks:
   - kafka-network
   
 broker:
  image: confluentinc/cp-server:5.5.1
  hostname: broker
  container_name: broker
  depends_on:
   - zookeeper
  ports:
   - "9092:9092"
  environment:
   KAFKA_BROKER_ID: 1
   KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
   KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
   KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
   KAFKA_LOG_SEGMENT_BYTES: 5000000
   KAFKA_DELETE_TOPIC_ENABLE: 'true'
   KAFKA_NUM_PARTITION: 2
   KAFKA_DEFAULT_REPLICATION_FACTOR: 1
   KAFKA_MIN_INSYNC_REPLICAS: 1
   KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 30000
   KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 6000
   KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
  
  networks:
   - kafka-network
 
 schema-registry:
  image: confluentinc/cp-schema-registry:5.5.1
  hostname: schema-registry
  container_name: schema-registry
  depends_on:
   - zookeeper
   - broker
  ports:
   - "8081:8081"
  environment:
   SCHEMA_REGISTRY_HOST_NAME: schema-registry
   SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  networks:
   - kafka-network

networks:
 kafka-network: