version: "2"
services:
  oracle:
   image: wnameless/oracle-xe-11g-r2
   container_name: oracle
   ports:
     - "49161:1521"
   networks:
     - webserver-network
  payara:
   image: payara/server-full
   container_name: payara
   ports:
     - "4849:4848"
     - "8082:8080"
   networks:
     - webserver-network
   volumes:
     - /Share:/opt/payara/deployments
   depends_on:
     - oracle
networks:
  webserver-network: